name: ortotech
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  provider: ^6.1.2
  percent_indicator: ^4.0.4
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  path: ^1.9.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.0
  video_player: ^2.9.2
  file_picker: ^8.1.4
  firebase_storage: ^12.3.7
  url_launcher: ^6.3.1
  intl: ^0.20.1
  pie_chart: ^5.4.0
  flick_video_player: ^0.9.0
  firebase_app_check: ^0.3.1+6
  youtube_player_flutter: ^9.1.1
  flutter_pdfview: ^1.3.4
  permission_handler: ^11.3.1
  dio: ^5.7.0
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/
    
  fonts:
    - family: SuperCreamy
      fonts:
        - asset: assets/fonts/SuperCreamy-OGAPp.ttf

  uses-material-design: true
